### ISSUE TITLE
Grass eaten by animals regrows much faster with deco installed

### ISSUE THREAD

**Issue by Justin-Erwin** [BTW-Community/Deco-Addon-2#48] opened 2021-11-05 16:47 UTC
From what I can tell, the addition seams to come from grass re-growing at night with torch light, though might be independent of that. I am curtain this is not the aesthetic grass Deco adds that grows in dark places. That "grass" shows up as a different texture in the TP pack I'm using.

**Comment by ammoore00** [comment] 2021-11-06 19:18
Yeah that's definitely the case. Grass and animals as a whole need significant work on the BTW end of things so I'm not particularly concerned with it for deco honestly.

**Comment by ammoore00** [comment] 2021-11-06 19:19
Closing this as "not a bug" for now given that aforementioned grass reworks will be coming for BTW.

**Closed by ammoore00** 2021-11-06 19:19 UTC

**Comment by Justin-Erwin** [comment] 2021-11-06 19:58
I definitely wasn't complaining or hoping you would change it, lol! At least not until the BTW side is fixed. The Deco difference doesn't stop the too-late-to-fix-it snowballing effect; so, I'm assuming the CE rework will be a different method. Your half eaten grass block idea should work well though. Way prettier and less tedious than my dotting of fence posts on large fields do currently... as I refuse to do grass roofs. :) Whether you go with that or something else on the field grass side of things, I look forward to seeing how you all tackle it!
